{% set name = "fixedwidth" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/FixedWidth-{{ version }}.tar.gz
  sha256: 472fe49c93dff14975cb8ea5bf6a7ef4c42343a7a1b494993640c6580be3de93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - fixedwidth
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ShawnMilo/fixedwidth
  summary: Two-way fixed-width <--> Python dict converter.
  license: BSD-Source-Code
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
